# Cálculo Numérico &mdash; Decomposição LU

> **Atividade** (Sendo aprimorada):
> 1. Adapte o código acima para fazer com que a função `solve_triangular_superior()` também retorno o número de operações (somas, produtos, divisões e subtrações numéricas) que foram realizadas. (**Dica**: A resposta é $n^2$; tente deduzir este valor formalmente).
> 2. Adapte o código acima para fazer o processo análogo (também contando operações), mas com matrizes triangulares _inferiores_.
> 3. Adapte o algoritmo de Crout&ndash;Dolittle, para fazer com que ele também retorne o número de operações realizadas.
> 4. Utilize as funções criadas no passo anterior para criar uma função que recebe uma matriz $A$, um inteiro positivo $n$ e um vetor $b$ e
>     - Decompõe a matriz $A$ como $A=LU$.
>     - Resolve o sistema linear $A^n x = b$, com aplicações sucessivas das funções criadas nos passos 1. e 2.
>     - Conta o número de operações.
> 5. Adapte o algoritmo de resolução de sistemas lineares da aula 9 para que ele conte o número de operações realizadas.
> 6. Adapte o algoritmo abaixo, que realiza o produto de duas matrizes $A$ e $B$, para que ele também conte o número de operações realizadas.
> 7. Crie uma matriz aleatória $A$ de ordem $4\times 4$ e um vetor $b$ de tamanho $4$, e resolva o sistema $A^{20}x = b$ por dois modos:
>     - Utilizando o método do passo 4;
>     - Calculando o produto $A^{20}=A\cdot A\cdots A$ com o algoritmo do passo 6, e resolvendo o sistema $(A^n)x = b$ diretamente com o algoritmo do passo 5.
>
>     Compare os números de operações e os resultados.

In [1]:
import numpy as np

    Implemetação primeira atividade proposta:

In [2]:
def solve_triangular_superior(U, b):
    contador=int(0)
    """Resolve um sistema triangular superior do tipo Ux = b.

    Parametros obrigatorios
    ----------
    U : Array-like de dimensao 2
        Matriz quadrada triangular superior inversível

    b : Array-like de dimensão 1
        Vetor independente

    Saída
    ----------
    x : Array-like de dimensão 1
        Solução do sistema Ux = b"""
    
    n = U.shape[0]          # Ordem das matrizes
    
    # Cópias usuais para evitar problemas
    x = b.copy().reshape(n)

    # Vai linha-a-linha, de baixo para cima, escalonando a matriz utilizando o pivô na diagonal
                        
    for i in range(n-1,-1,-1):
        x[i] /= U[i,i]     # Normaliza a i-ésima linha

        contador+=1 #Apenas uma operação +
        for j in range(i-1,-1,-1):
            x[j] -= U[j,i]*x[i]     # Pivoteia a i-ésima coluna, utilizando a entrada diagonal como pivô

            contador+=2 #Duas operações - e *

    return x, contador

Teste da implementação:

In [3]:
U = 20*np.random.rand(4,4) -10 # Matriz triangular aleatória com entradas em [-10,10]

for i in range(4):
    for j in range(i):
        U[i,j]=0.0        # Aniquila as entradas abaixo da diagonal principal para deixar triangular superior
        
        
b = 20*np.random.rand(4) - 10 # Vetor aleatório com entradas em [-10,10]

x,y = solve_triangular_superior(U,b) # Solução pretendida do sistema Ux = b

print(f"\nA matriz U é dada por\n{U}")
print(f"\nO vetor b é dada por\n{b}")
print(f"\nO vetor x é dada por\n{x}")
print(f"\nO vetor Ux é dada por\n{U@x}")
print("\nO número total de operações é:\n",y)


A matriz U é dada por
[[-2.96230495 -6.93793326 -3.59171692 -9.39641937]
 [ 0.         -4.74104849 -5.1797611  -4.41757333]
 [ 0.          0.         -2.56573214  9.27141473]
 [ 0.          0.          0.         -6.46013654]]

O vetor b é dada por
[-7.39938383  8.35570855  4.05959058 -1.71134582]

O vetor x é dada por
[ 5.5219571  -1.32644745 -0.62497286  0.26490862]

O vetor Ux é dada por
[-7.39938383  8.35570855  4.05959058 -1.71134582]

O número total de operações é:
 16


    Implementação da segunda atividade proposta:

In [4]:
def solve_triangular_inferior(L, b):
    contador=int(0)
    """Resolve um sistema triangular inferior do tipo Lx = b.

    Parametros obrigatorios
    ----------
    L : Array-like de dimensao 2
        Matriz quadrada triangular superior inversível

    b : Array-like de dimensão 1
        Vetor independente

    Saída
    ----------
    x : Array-like de dimensão 1
        Solução do sistema Lx = b"""
    
    n = L.shape[0]          # Ordem das matrizes
    
    # Cópias usuais para evitar problemas
    x = b.copy().reshape(n)

    # Vai linha-a-linha, de cima para baixo, escalonando a matriz utilizando o pivô na diagonal
                        
    for i in range(n):
        x[i] /= L[i,i]     # Normaliza a i-ésima linha
        contador+=1 #Apenas uma operação +

        for j in range(i+1,n):
            x[j] -= L[j,i]*x[i]     # Pivoteia a i-ésima coluna, utilizando a entrada diagonal como pivô

            contador+=2 #Duas operações - e *

    return x, contador

Teste da implementação:

In [5]:
L = 20*np.random.rand(4,4) -10 # Matriz triangular aleatória com entradas em [-10,10]

for i in range(4):
    for j in range(i):
        L[j,i]=0.0        # Aniquila as entradas abaixo da diagonal principal para deixar triangular superior
        
        
b = 20*np.random.rand(4) - 10 # Vetor aleatório com entradas em [-10,10]

x,y = solve_triangular_inferior(L,b) # Solução pretendida do sistema Ux = b

print(f"\nA matriz L é dada por\n{L}")
print(f"\nO vetor b é dado por\n{b}")
print(f"\nO vetor x é dado por\n{x}")
print(f"\nO vetor Lx é dado por\n{L@x}")
print("\nO número total de operações é:\n",y)



A matriz L é dada por
[[-1.11589326  0.          0.          0.        ]
 [ 9.4718315  -5.54903636  0.          0.        ]
 [ 9.77090757 -0.9206519   6.49020236  0.        ]
 [-5.9360509   2.79615859  2.36256042  0.61457087]]

O vetor b é dado por
[ 4.48368013  5.21083082 -6.20784551  9.29505417]

O vetor x é dado por
[-4.01801882 -7.7975391   3.98647444 -3.53293805]

O vetor Lx é dado por
[ 4.48368013  5.21083082 -6.20784551  9.29505417]

O número total de operações é:
 16


    Implementação da terceira atividade proposta:

In [6]:
def crout_dolittle(A):
    contador=int(0)
    ''' Decomposição LU de A pelo algoritmo de Crout'''

    m,n = np.shape(A)

    L = np.zeros((n,n))
    U = np.zeros((n,n))
    

    L[0,0] = 1          # Escolha de Dolittle
    U[0,0] = A[0,0]

    for j in range(1,n):
        U[0,j] = A[0,j]/L[0,0]      # Determina a primeira linha de U
        L[j,0] = A[j,0]/U[0,0]      # Determina a primeira coluna de L
        contador+=2

    for i in range(1,n):
        L[i,i]=1        # Escolha de Dolittle
        U[i,i] = A[i,i] - sum([L[i,k]*U[k,i] for k in range(i)])
        
        contador+=i
        contador+=i-1
        contador+=1
 
        for j in range(i+1,n):
            U[i,j] = (A[i,j] - sum([L[i,k]*U[k,j] for k in range(i)]))/L[i,i]       # Determina a i-ésima linha de U
            contador+=i
            contador+=i-1
            contador+=2
            L[j,i] = (A[j][i] - sum([L[j,k]*U[k,i] for k in range(i)]))/U[i,i]      # Determina a i-ésima coluna de L
            contador+=i
            contador+=i-1
            contador+=2
            
            
    return L , U , contador

Teste da implementação:

In [7]:
A = 20*np.random.rand(4,4) - 10.0       # Matriz aleatória com entradas entre -10 e 10

L , U , contador = crout_dolittle(A)               # Decomposição LU de $A$

print(f"A matriz A é dada por\n{A}")
print(f"\nA matriz L é dada por\n{L}")
print(f"\nA matriz U é dada por\n{U}")
print(f"\n\nO produto LU é dado por\n{L@U}")
print("\nO número total de operações é:\n",contador)

A matriz A é dada por
[[ 9.54292358 -4.54510702 -8.63118123 -2.86643318]
 [ 0.54543665 -7.37200011  3.5012092   9.35812938]
 [-3.21626719  6.47015819  5.43072265 -8.24442619]
 [-2.71918803  5.70740735  1.67152786  9.39811193]]

A matriz L é dada por
[[ 1.          0.          0.          0.        ]
 [ 0.05715614  1.          0.          0.        ]
 [-0.33703164 -0.6943421   1.          0.        ]
 [-0.28494287 -0.62038462  0.31920329  1.        ]]

A matriz U é dada por
[[ 9.54292358 -4.54510702 -8.63118123 -2.86643318]
 [ 0.         -7.11221935  3.99453418  9.52196363]
 [ 0.          0.          5.29531473 -2.59900465]
 [ 0.          0.          0.         15.31823287]]


O produto LU é dado por
[[ 9.54292358 -4.54510702 -8.63118123 -2.86643318]
 [ 0.54543665 -7.37200011  3.5012092   9.35812938]
 [-3.21626719  6.47015819  5.43072265 -8.24442619]
 [-2.71918803  5.70740735  1.67152786  9.39811193]]

O número total de operações é:
 40


    Implementação da quarta atividade proposta:

In [8]:
def solve_matriz(A,n,b):
   
    m=A.shape[0]

    L,U,contador=crout_dolittle(A)

    x=b.copy().reshape(m)

    for i in range (n):
        y,cont=solve_triangular_inferior(L,x)
        x,cont_2=solve_triangular_superior(U,y)
        contador+=cont+cont_2

    return x , contador

Teste da implementação:

In [9]:
A=np.random.rand(4,4)
b=np.random.rand(4)
n=int(10)

result, num=solve_matriz(A,n,b)

print(f"\nA matriz L é dada por\n{A}")
print(f"\nO vetor b é dado por\n{b}")
print("\nA potência é dada por\n",n)
print("\nA resposta é dada por\n",result)
print("\nO número total de operações é:\n",num)


A matriz L é dada por
[[0.17725818 0.20167321 0.70533473 0.72029633]
 [0.94945923 0.40208219 0.85167121 0.74934114]
 [0.82469499 0.69067922 0.41082976 0.77943069]
 [0.6238493  0.08220315 0.80484583 0.05432833]]

O vetor b é dado por
[0.91019777 0.94333272 0.50594542 0.1720234 ]

A potência é dada por
 10

A resposta é dada por
 [-5745291.44208974  6653581.8409547   4945186.03074534 -3694202.70592145]

O número total de operações é:
 360


    Implementação da quinta atividade proposta:

In [10]:
import numpy as np

def pivot_partial(x):
    return np.argmax(abs(x))

def ref(A, tol=None, pivot=pivot_partial, verbose=False):

    #Faz cópias
    T = np.array(A).astype(float)
    posicao_pivos = []
    #Grava o tamanho
    n_linhas, n_colunas = np.shape(T)

    if tol == None:
        # Mesma que no Octave
        tol = 2**(-52) * np.max(abs(T)) * max(n_linhas, n_colunas)
     #end if

    #Vê quantos pivôs já foram achados
    n_pivos = 0

    #Linhas na qual trabalharemos
    j = 0

    if verbose:
        print("Vamos escalonar parcialmente a matriz")
        print(T)
    #end if

    num_op = 0
    while (j < n_colunas and n_pivos < n_linhas):
        if verbose:
            print("=====")
            print(f"Vamos pivotear a coluna {j}.")
        #end if

        #Encontra o pivô
        p = pivot(T[n_pivos:, j]) + n_pivos
        if abs(T[p, j]) > tol:
            #Encontramos um pivô.
            #Troca linhas caso necessário
            if p != n_pivos:

                for k in range(j, n_colunas):
                    temp = T[p, k]
                    T[p, k] = T[n_pivos, k]
                    T[n_pivos, k] = temp

                #end for
                if verbose:
                    print(f"Precisamos trocar a linha {n_pivos} com a linha {p}."                    )
                    print(T)
                #end if

                p = n_pivos
            #end if

            #Pivoteia abaixo
            for k in range(p + 1, n_linhas):
                if abs(T[k, j]) > tol:
                    multiplicador = T[k, j] / T[p, j]
                    num_op += 1
                    T[k, j + 1:] = T[k, j + 1:] - multiplicador * T[p, j + 1:]
                    num_op += n_colunas - 1 - j
                    T[k, j] = 0
                #end if
            #end for
            if verbose:
                print("Aniquila as entradas abaixo:")
                print(T)
            #end if

            #Conta o pivô a mais
            n_pivos += 1
            posicao_pivos.append(j)
        else:
            if verbose:
                print(f"A coluna {j} nao tem pivo.")
        #end if
        #passa pra próxima coluna
        j += 1
    #end while

    if verbose:
        print(f"Numero de operacoes: {num_op}")
    #end if-else
    return [T, posicao_pivos],num_op


#end def


def retrossub(A, pospiv=[], tol=None, verbose=False):
    contador=int(0)
    

    #Faz as cópias usuais para evitar problemas
    R = np.array(A).astype(float)
    m, n = np.shape(R)

    if tol == None:
        tol = 2**(-30) * np.max(abs(R))
    #end if

    if verbose:
        print("Vamos fazer retrosubstituição na matriz")
        print(A)
    #end if

    #caso nao saibamos as posições dos pivos, temos que encontrá-los
    if pospiv == []:
        if verbose:
            print('Nâo foi dada a posição dos pivôs da matriz.')
            print('Vamos encontrá-los:')
        #end if
        i = 0
        j = 0
        while (i < m):
            while abs(R[i, j]) < tol and j < n:
                j += 1
            #end while

            if j == n:
                break
            else:
                pospiv.append(j)
                i += 1
            #end if-else
        #end while
    #end if

    if verbose:
        print(f"Os pivôs estao nas colunas {pospiv}")
        print()
    #end if
    numero_de_pivos = len(pospiv)
    for i in range(numero_de_pivos - 1, -1, -1):
        if verbose:
            print('=====')
        #end if
        #Normaliza o pivô, caso necessário
        if abs(R[i, pospiv[i]] - 1) > tol:
            R[i, pospiv[i] + 1:] /= R[i, pospiv[i]]
            R[i, pospiv[i]] = 1
            contador+=1
            if verbose:
                print(f"Vamos normalizar o pivo na linha {i}.")
                print(R)
                print()
            #end if
        #end if

        #Aniquila as entradas acima
        if verbose:
            print(
                f"Vamos aniquilar as entradas acima do pivo na posição ({i},{pospiv[i]})."
            )
        #end if
        for k in range(i - 1, -1, -1):
            R[k, pospiv[i] + 1:] -= R[k, pospiv[i]] * R[i, pospiv[i] + 1:]
            R[k, pospiv[i]] = 0
            contador+=2
        #end for

        if verbose:
            print(R)
        #end if
    #end for

    return [R, pospiv],contador


#end function


def rref(A, tol=None, pivot=pivot_partial, verbose=False):

    T,cont = ref(A, tol=tol, pivot=pivot, verbose=verbose)

    B,contador= retrossub(T[0], pospiv=T[1], tol=tol, verbose=verbose)
    return B, cont+contador


#end def

Teste da implementação:

In [11]:
Mat=np.random.rand(4,4)
resultado,contador=rref(Mat)

print("\nA Matriz é:\n",Mat)
print("\nO resultado é\n",resultado)
print("\nO número de iterações é:\n",contador)


A Matriz é:
 [[0.86197924 0.19283188 0.82921937 0.32580215]
 [0.02000003 0.15765842 0.78806179 0.23028459]
 [0.07651345 0.44126013 0.28666692 0.65077854]
 [0.66318903 0.00602116 0.90547316 0.54278008]]

O resultado é
 [array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]]), [0, 1, 2, 3]]

O número de iterações é:
 36


    Implementaçao sexta atividade proposta:

In [12]:
def matmul(A,B,contador=0):

    """Produto de matrizes quadradas de mesma ordem

    Parametros obrigatorios
    ----------
    A , B : Array-like de dimensao 2
        Matrizes quadradas de mesma ordem

    Saída
    ----------
    C : Array-like de dimensão 2
        Produto C = AB"""
    
    n=A.shape[0]
    
    C = np.zeros((n,n))
    
    for i in range(n):
        for j in range(n):
            for k in range(n):
                C[i,j] += A[i,k]*B[k,j]
                contador+=2
                
    return C,contador

Teste da implementação:

In [13]:
L = np.random.rand(4,4)  # Matriz triangular aleatória com entradas em [-10,10]
U = np.random.rand(4,4) 

x,y=matmul(L,U)

print("\nMatriz para multiplicação L:\n",L)
print("\nMatriz para multiplicação U:\n",U)
print("\nA Matriz multiplicada é:\n",x,"\nO total de operações é:\n",y)


Matriz para multiplicação L:
 [[0.49279677 0.49688656 0.1916945  0.54144988]
 [0.95521545 0.27556371 0.44540158 0.65539599]
 [0.67769174 0.37680599 0.26526508 0.61897818]
 [0.66130804 0.78400138 0.40002939 0.90449679]]

Matriz para multiplicação U:
 [[0.46046971 0.81760808 0.85448647 0.62369216]
 [0.78710282 0.15453463 0.68150776 0.10527134]
 [0.79789359 0.56045687 0.54045205 0.63846192]
 [0.17892975 0.93157428 0.28797112 0.6648381 ]]

A Matriz multiplicada é:
 [[0.86785211 1.09153809 1.01924384 0.84202755]
 [1.12939766 1.68375444 1.4334708  1.34487352]
 [0.93104849 1.3376096  1.15748552 1.04321982]
 [1.40262429 1.72865133 1.57604745 1.35173298]] 
O total de operações é:
 128


    Implementação da setima atividade proposta:

In [14]:
import numpy as np

#Criação de variaveis aleatórias:
A=np.random.rand(4,4)
b=np.random.rand(4)
n=int(20)
contador=0

#Resolução pelo método do 4º exercício:
vet, num = solve_matriz(A,n,b)


#Calcula o método do 5º exercício:
cont2=0
a=A.copy()
for i in range (n-1):
    A,conti=matmul(a,A)
    cont2+=conti
    i+=1
B=np.column_stack((A,b))
res,aux=rref(B, tol=None, pivot=pivot_partial, verbose=False)
x2=res[0]
contador+=aux+cont2
resposta=x2[:,-1]


print("\nA Matriz inical é:\n",A)
print("\nO Vetor inicial:\n",b)
print("\nA potência é dada por\n",n)
print("\nResposta método 5:\n",resposta)
print("\nNúmero de iterações método 4:\n",contador)
print("\nResposta método 4:\n",vet)
print("\nNúmero de iterações método 4:\n",num)


A Matriz inical é:
 [[239259.80640057 142712.18558899  93787.96148535  90578.49904418]
 [113366.0594034   67619.8746144   44438.60326156  42917.89606367]
 [178676.14353297 106575.62312623  70039.6423458   67642.85710874]
 [255011.33595451 152107.55893995  99962.43712907  96541.68160338]]

O Vetor inicial:
 [0.69225034 0.9386247  0.40508163 0.31437803]

A potência é dada por
 20

Resposta método 5:
 [0. 0. 1. 0.]

Número de iterações método 4:
 2465

Resposta método 4:
 [ 1.06994414e+21  5.33526353e+20  4.58327590e+19 -3.71427992e+21]

Número de iterações método 4:
 680
